# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUhQfjzRGMzPj-ghxTdybPwnRgt14ZVA
"""

import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

# -----------------------------------------------------------
# 1. Generate Synthetic Dataset
# -----------------------------------------------------------
X, y = make_classification(n_samples=500, n_features=10, n_informative=5,
                           n_redundant=2, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -----------------------------------------------------------
# 2. Custom Logistic Regression (NumPy Only)
# -----------------------------------------------------------
class CustomLogisticRegression:

    def __init__(self, lr=0.01, num_iters=1000, lambda_reg=0.01):
        self.lr = lr
        self.num_iters = num_iters
        self.lambda_reg = lambda_reg

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def compute_cost(self, X, y):
        m = len(y)
        h = self.sigmoid(X.dot(self.weights) + self.bias)
        cost = -(1/m) * np.sum(
            y*np.log(h + 1e-9) + (1-y)*np.log(1-h + 1e-9)
        )
        reg_cost = (self.lambda_reg/(2*m)) * np.sum(self.weights**2)
        return cost + reg_cost

    def fit(self, X, y):
        m, n = X.shape
        self.weights = np.zeros(n)
        self.bias = 0

        for _ in range(self.num_iters):
            linear_model = X.dot(self.weights) + self.bias
            h = self.sigmoid(linear_model)

            dw = (1/m) * X.T.dot(h - y) + (self.lambda_reg/m)*self.weights
            db = (1/m) * np.sum(h - y)

            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        y_pred_prob = self.sigmoid(X.dot(self.weights) + self.bias)
        return np.where(y_pred_prob >= 0.5, 1, 0)


# -----------------------------------------------------------
# 3. Train Custom Logistic Regression
# -----------------------------------------------------------
custom_model = CustomLogisticRegression(lr=0.01, num_iters=1000, lambda_reg=0.1)
custom_model.fit(X_train, y_train)
y_pred_custom = custom_model.predict(X_test)

# -----------------------------------------------------------
# 4. Train Scikit-Learn LogisticRegression
# -----------------------------------------------------------
sk_model = LogisticRegression(max_iter=1000)
sk_model.fit(X_train, y_train)
y_pred_sk = sk_model.predict(X_test)

# -----------------------------------------------------------
# 5. Evaluation Metrics
# -----------------------------------------------------------
def evaluate(name, y_true, y_pred):
    print(f"\n--- {name} ---")
    print("Accuracy :", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred))
    print("Recall   :", recall_score(y_true, y_pred))

evaluate("Custom Logistic Regression", y_test, y_pred_custom)
evaluate("Scikit-Learn Logistic Regression", y_test, y_pred_sk)